task: wmt_en_uk
dataset_path: google/wmt24pp
dataset_name: en-uk_UA
output_type: generate_until
#training_split: train
#validation_split: train
training_split: train
validation_split: train
test_split: train
fewshot_split: train
doc_to_text: "Англійський текст:\n{{source}}\n\nПереклад українською:"
doc_to_target: "{{target}}"
generation_kwargs:
  until:
    - "==sdfAcxbvgg/=/=/="
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
