tag:
  - llama
task: arc_challenge_uk
dataset_path: INSAIT-Institute/arc-challenge_ukr
output_type: generate_until
training_split: train
validation_split: validation
test_split: test
fewshot_split: train
doc_to_text: 'Маючи наступне запитання та чотири варіанти відповіді (A, B, C and D), оберіть найкращу відповідь.\Питання: {{question.strip()}}\nA. {{choices.text[0]}}\nB. {{choices.text[1]}}\nC. {{choices.text[2]}}{% if choices.text|length > 3 %}\nD. {{choices.text[3]}}{% endif %}\nВаша відповідь повинна завершуватися фразою "Найкраща відповідь — [літера_відповіді]", де [літера_відповіді] — це одна з A, B, C або D.'
gen_prefix: 'Найкраща відповідь - '
fewshot_delimiter: "\n\n"
doc_to_target: "{{ 'ABCD'[answerKey|int - 1] if answerKey|string in '1234' else answerKey }}"
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 100
  until:
    - "\n\n"
    - "."
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: remove_whitespace
    filter:
      - function: remove_whitespace
      - function: take_first
metadata:
  version: 1.0