task: arc_easy_uk
dataset_path: INSAIT-Institute/arc-easy_ukr
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
doc_to_text: "Питання: {{question}}\nВідповідь:"
doc_to_target: "{{choices.label.index(answerKey)}}"
doc_to_choice: "{{choices.text}}"
should_decontaminate: true
doc_to_decontamination_query: "Питання: {{question}}\nВідповідь:"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0