task: triviaqa_uk
dataset_path: INSAIT-Institute/trivia_qa_ukr
output_type: generate_until
training_split: validation
validation_split: validation
test_split: validation
doc_to_text: "Питання: {{question}}?\nВідповідь:"
doc_to_target: "{{answer.aliases}}"
should_decontaminate: true
doc_to_decontamination_query: question
generation_kwargs:
  until:
    - "\n"
    - "."
    - ","
  do_sample: false
  temperature: 0.0
filter_list:
  - name: remove_whitespace
    filter:
      - function: remove_whitespace
      - function: take_first
target_delimiter: " "
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  version: 3.0